### ISSUE TITLE
Refactor the Requirements

### ISSUE THREAD

**Issue by Legervad** [bounswe/bounswe2023group6#238]
### Problem

After getting some feedback on the overall project design, the requirements need refactoring.

### Solution

A meeting has been arranged to go over the requirements and come up with possible changes on the overall design.

### Deadline

05.10.2023 - Thursday - 23.59

**Comment by ahmetkudu** [comment]
Five ideas for the gaming domain-specific:
1- _Walk-through:_ There may be hints for sections that some gamers cannot complete.
2- _Gaming NEWS:_ eFootball 2024 on the Field: What Does Konami's New Game Promise?
3- _Saling:_ Players' ability to sell their character (see bynogame.com)
4- _PC-Builds:_ There may be a section like building a PC, which explains how sufficient a PC is for which game.
5- _Publishers:_ There may be a section for publishers.

**Comment by smelihportakal** [comment]
Uygulama bir oyunlar hakkında bazı bilgileri girme platformu olacak. Kullanıcılar online oyun, hikayeli oyun, hikayeli oyun, masa oyunu gibi bazı hazır oyun templateleri kullanarak oyun hakkındaki bilgileri doldurabilecek. ve bu templateler üzerinde bazı değiştirmeler eklemeler yapabilir belki. mesela oyun templatei olarak mekanlar, karakterler gibi bölümler olabilir. Kullanıcı isterse bu bölümlerden bazılarını çıkartabilir yada başka bir bölümü sayfaya ekleyip ona göre doldurabilir.

**Comment by ahmetkudu** [comment]
I deleted some event-related requirements in the  21.10.2023 backend team meeting because Alper Hoca said that "You can remove those" since we will be adding game-specific requirements. 
I added some requirements about game pages as you see in the [1.2.3 Game Pages Requirements.](https://github.com/bounswe/bounswe2023group6/wiki/Requirements) 
The below image also shows those are done:
![Screenshot 2023-10-23 at 21 24 43](https://github.com/bounswe/bounswe2023group6/assets/74921213/075cf24c-a4bd-4ab7-84a5-bb122959d579)

**Comment by Legervad** [comment]
Necessary actions have been taken regarding this issue. I'm closing it.
