### ISSUE TITLE
Preparing a Milestone Presentation to the Customer

### ISSUE THREAD

**Issue by ahmetkudu** [bounswe/bounswe2023group6#297]
### Problem

We will present the milestone to our customers on 31.10.2023. By this date, the backend, frontend, and mobile teams will have completed their login authorizations (registration, login, log out, change password, and forgot password). The presenters will apply the user scenarios the teams have prepared in advance during the presentation. Positive and negative feedback will be received during the presentation with at least two note-takers we have determined in advance. We can try to show a few more features, such as posting on the forum. If there are half-baked features, the remaining works will be mocked and shown.

The presentation time will be 10 min. 

### Solution

- Determine note-takers
- Determine presenters.
- Determine user scenarios that will be presented by the backend/frontend and mobile team members.

### Additional notes

1- Don't implement anything after the deadline so that we can avoid any problems during the presentation.
2- We will not present UML, which will be completed on 03.11.2023. 
3- On the registration screen, don't only enter information such as name, surname, and email, but also enter the fields that will be used for the platform.

### Reviewers

Emre Türker

### Deadline

31.10.2023 - 23.59

**Comment by ahmetkudu** [comment]
Note Takers: @ahmetkudu, @emresin12 , @ohbahadiroglu 
Presenters: @mustafakucuk-dev(mobile) or @smelihportakal(mobile), @omertalib42(frontend)

**Comment by ahmetkudu** [comment]
@Legervad, could you review this issue? If it is okay, please close it.

**Comment by ahmetkudu** [comment]
Positive feedbacks:
- It's good that the recommendation provides platform specificity.
- It's good that the Recommendation recommends games based on avatars/fields.
- It's good that our gaming platform differentiates from a standard gaming site/forum.

Negative feedbacks:
- The mock game page should have shown more things
- More care should have been taken for games that always used the same logo
- UI could be better for mock
- Username information in registration is sufficient.
- It is not clear whether uploading the image in registration is optional or not.

**Comment by emresin12** [comment]
Here are the Feedback and Action Items from Milestone 1 Presentation @ahmetkudu 

During our first milestone presentation, we received valuable feedback from the customer. This feedback will guide our improvements and refinements as we proceed. Below are the highlighted points and associated action items.

Game Icons:

- Each game should have a distinct icon representing it, instead of a common icon for all games.

   Action Item: Design and integrate unique icons for each game listed on the platform.
Game Navigation:
- Currently, games are navigated through URLs; this should be shifted to a UI-based navigation system.
   Action Item: Develop a user-friendly UI for game navigation.
Game Ratings:
- The current rating system was questioned.
  Action Item: Review and possibly redesign the rating system to ensure it meets the customer's expectations.
Game Interaction:
- The platform should facilitate interaction with the games.
  Action Item: Design and implement features that allow users to interact with the games.
Game Post Dates and Release Dates:
- The dates on game posts are generic. Additionally, users may want to know the release date of the games.
  Action Item: Include specific post dates and game release dates on the platform.
Discussion Platform:
- Users should have a platform to discuss games.
  Action Item: Create a discussion forum or integrate a discussion platform for each game.
Communication among LFG (Looking For Group) Users:
- The current communication system among LFG users was questioned.
  Action Item: Clarify or redesign the communication system to ensure smooth interactions among LFG users.
Competitive Edge:
- Define what gives our platform a competitive edge in the market.
  Action Item: Establish and articulate the unique selling propositions (USPs) of our platform.
Character Recommendation:
- Functionality for recommending characters based on character similarity was inquired about.
  Action Item: Explore and possibly develop a character recommendation system based on character similarities.
Games You May Like Section:
- The "Games You May Like" section was questioned.
  Action Item: Review and refine the algorithm and presentation of the "Games You May Like" section to ensure relevance and accuracy.

These feedback points provide a roadmap for refining our platform to better meet the customer’s and end-users’ needs. It's crucial that we address these points promptly and effectively as we move towards the next milestone.

**Comment by ahmetkudu** [comment]
@Legervad, could you review this issue? Kindly close it if it okay.

**Comment by Legervad** [comment]
Good job guys, closing it.
